version: "3"

services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/caddy/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
