FROM node:20.10.0 AS build
WORKDIR /app/frontend
COPY ./frontend/ ./

RUN npm run build

FROM caddy:latest
COPY --from=build /app/frontend/dist /static
CMD ["caddy", "file-server", "--root","/static", "--domain", "eujbinlsegnoiujt123.freemyip.com"]